### ISSUE TITLE
Android audio stream buffer memory

### ISSUE THREAD

**Issue by aixil123** [gezhaoyou/AndroidRtmpPublisher#4]
English:
Hello, I'm going to build your project in androidx version and make a reference sample, when pushing flow, prompt the audio stream buffer memory collective code is as follows: in the class file: CodecManager if (inBufferIndex > = 0) {
ByteBuffer bb = inBuffers [inBufferIndex];
Bb. The clear ();
Bb. Put (data, 0, the data length); / / here is the problem of memory, hope you can answer, or maintenance projects together, so, windos or android, to make more feasible projects, thank you, if you are confused I can be your upgrade for androidx project sent to you, build are using the latest version of the android studio4.1, while my phone is 13640731316, if you are willing to help me, or more in-depth in audio communication to provide feasible solutions together, I would be grateful.
Chinese:
您好，我将您的项目构建在androidx版本并作出示例参考，在推流时，音频流缓冲提示内存溢出集体代码如下:类文件:CodecManager中if (inBufferIndex >= 0) {
ByteBuffer bb = inBuffers[inBufferIndex];
bb.clear();
bb.put(data, 0, data.length);//这里是问题所在，内存溢出，希望您能够做出回答，或者一起共同维护项目，so,windos或者android，做出更多可行的项目,谢谢,您如果感到困惑我可以将您的升级为androidx的项目发送给您，构建都采用最新版本android studio4.1,另外我的电话13640731316，如果您愿意帮助我，或者一起为更多深入音视频交流提供可行方案，我将感激不尽。

**Comment by aixil123** [comment]
E/AndroidRuntime: FATAL EXCEPTION: Thread-3
    Process: com.spark.live.kit, PID: 930
    java.nio.BufferOverflowException
        at java.nio.DirectByteBuffer.put(DirectByteBuffer.java:298)
        at com.spark.live.sdk.media.codec.CodecManager.handleAudioData(CodecManager.java:169)
        at com.spark.live.sdk.engine.SimpleLivePulisherEngine$AVDataCallback.onAudioData(SimpleLivePulisherEngine.java:333)
        at com.spark.live.sdk.media.device.audio.AudioRecorderManager.run(AudioRecorderManager.java:158)
D/ActivityThread: Won't deliver top position change in state=5
